# Generated by Django 2.0.7 on 2018-08-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_auto_20180815_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='media/%y/%m/%d'),
        ),
    ]
